config/routes.rb
Rails.application.routes.draw do
  resources :headlines
  resources :members 

  get '/short/:short_url', to: 'short#show'

  get '/expert', to: 'expert#index'

  root :to => "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/headline.rb
class Headline 
  include ActiveGraph::Node
  property :heading, type: String

  has_many :in, :experts, type: :connection, model_class: 'Member'

  validates :heading, presence: true
end

app/models/member.rb
require 'digest'

class Member
  include ActiveGraph::Node
  property :name, type: String
  property :url, type: String
  property :short_url, type: String

  has_many :out, :friends, type: :FRIEND, model_class: self, labels: false, unique: true
  has_many :out, :headlines, type: :connection, model_class: 'Headline'

  validates :name, presence: true
  validates :url, presence: true

  before_save() {
    # Create short urls
    self.short_url = Digest::SHA1.hexdigest(url)[8..16]
  }

  after_save() {
    # Parse through the member url and retrieve header tag content
    UrlHeaderTagCrawlerWorker.perform_async(self.id)
  }

  def all_except_self
    members = Member.all.reject{|m| m == self }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/expert_controller.rb
class ExpertController < ApplicationController
  def index
    Rails.logger.info expert_params.inspect

    @result = []

    if expert_params['query']
      @member = Member.find_by(id: expert_params['member_id'])
      res = @member.friends.as(:f).headlines.where(heading: expert_params['query'].strip).pluck('f')

      if res.empty?
        res = Headline.where(heading: expert_params['query'].strip).experts.as(:e).pluck('e')
      end

      @result = res
    end
  end

  private
  def expert_params
    params.permit(:member_id, :query, :commit)
  end
end

app/controllers/headlines_controller.rb
class HeadlinesController < ApplicationController
  before_action :set_headline, only: %i[ show edit update destroy ]

  # GET /headlines or /headlines.json
  def index
    @headlines = Headline.all
  end

  # GET /headlines/1 or /headlines/1.json
  def show
  end

  # GET /headlines/new
  def new
    @headline = Headline.new
  end

  # GET /headlines/1/edit
  def edit
  end

  # POST /headlines or /headlines.json
  def create
    @headline = Headline.new(headline_params)

    respond_to do |format|
      if @headline.save
        format.html { redirect_to @headline, notice: "Headline was successfully created." }
        format.json { render :show, status: :created, location: @headline }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @headline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /headlines/1 or /headlines/1.json
  def update
    respond_to do |format|
      if @headline.update(headline_params)
        format.html { redirect_to @headline, notice: "Headline was successfully updated." }
        format.json { render :show, status: :ok, location: @headline }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @headline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /headlines/1 or /headlines/1.json
  def destroy
    @headline.destroy
    respond_to do |format|
      format.html { redirect_to headlines_url, notice: "Headline was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_headline
      @headline = Headline.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def headline_params
      params.require(:headline).permit(:heading)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)

        unless member_params['follow_member_id'].nil?
          follow_member = Member.find_by(id: member_params['follow_member_id'])

          if @member.friends.where(id: follow_member.id).empty?
            @member.friends << follow_member
          end
        end

        format.html { redirect_to @member, notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def unfriend
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:name, :url, :short_url, :follow_member_id)
    end
end

app/controllers/short_controller.rb
class ShortController < ApplicationController
  def show
    member = Member.find_by(short_url: short_params['short_url'])

    redirect_to member.nil? ?
      members_path
      : member.url
  end

  private
  def short_params
    params.permit(:short_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/headlines_helper.rb
module HeadlinesHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def decorate_short_url(member)
    "#{request.base_url}/short/#{member.short_url}"
  end
end

app/views/expert/index.html.erb
<h1>Expert Search</h1>

<p>
<%= form_tag expert_path, method: :get do %>
  <%= select_tag :member_id, options_for_select(Member.all.map {|m| [m.name, m.id]}, params[:member_id]) %>
  <%= text_field_tag :query, nil, :required => true %>
  <%= submit_tag("Search!") %>
<% end %>
</p>

<p>
  <table>
    <tr>
      <th>Name</td>
      <th>Show</td>
    </tr>
    <% @result.each do |r| %>
      <tr>
        <td><%= r.name %></td>
        <td><%= link_to 'Show', r %></td>
      </tr>
    <% end %>
  </table>
</p>

app/views/headlines/_form.html.erb
<%= form_with(model: headline, local: true) do |form| %>
  <% if headline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(headline.errors.count, "error") %> prohibited this headline from being saved:</h2>

      <ul>
        <% headline.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :heading %>
    <%= form.text_field :heading %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/headlines/edit.html.erb
<h1>Editing Headline</h1>

<%= render 'form', headline: @headline %>

<%= link_to 'Show', @headline %> |
<%= link_to 'Back', headlines_path %>

app/views/headlines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Headlines</h1>

<table>
  <thead>
    <tr>
      <th>Heading</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @headlines.each do |headline| %>
      <tr>
        <td><%= headline.heading %></td>
        <td><%= link_to 'Show', headline %></td>
        <td><%= link_to 'Edit', edit_headline_path(headline) %></td>
        <td><%= link_to 'Destroy', headline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Headline', new_headline_path %>

app/views/headlines/new.html.erb
<h1>New Headline</h1>

<%= render 'form', headline: @headline %>

<%= link_to 'Back', headlines_path %>

app/views/headlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Heading:</strong>
  <%= @headline.heading %>
</p>

<%= link_to 'Edit', edit_headline_path(@headline) %> |
<%= link_to 'Back', headlines_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EverlywellBackendChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Everlywell Backend Challenge</h1>

    Navigation:
    <%= link_to 'Members', members_path %> | <%= link_to 'Headlines', headlines_path %> | <%= link_to 'Expert Search', expert_path %>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= form_with(model: @member, local: true) do |form| %>
    <% if @member.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>
  
        <ul>
          <% @member.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :url %>
      <%= form.text_field :url %>
    </div>

    <div class="field">
      <%= form.label 'Follow new member' %>
      <%= form.collection_select :follow_member_id, @member.all_except_self,:id,:name, :include_blank => true %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Short url</th>
      <th>Friends</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.url %></td>
        <td><%= decorate_short_url(member) %></td>
        <td><%= member.friends.count %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Url:</strong>
  <a href=<%= @member.url %> target="_blank"><%= @member.url %></a>
</p>

<p>
  <strong>Short url:</strong>
  <a href=<%= decorate_short_url(@member) %> target="_blank"><%= decorate_short_url(@member) %></a>
</p>

<p>Friends <%= @member.friends.count %></p>

<h2>Headlines</h2>
<table>
  <% @member.headlines.each do |h| %>
    <tr>
      <td><%= h.heading %></td>
    </tr>
  <% end %>
</table>

<h2>Friends</h2>
<table>
  <% @member.friends.each do |f| %>
    <tr>
      <td><%= f.name %></td>
      <td><%= link_to 'Show', f %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>